// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Visma_Hackathon_SecurityAutomation_Web
{
    public partial class ClaimExpenseFraudDetectionModel
    {
        /// <summary>
        /// model input class for ClaimExpenseFraudDetectionModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"RefNbr")]
            public float RefNbr { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Employees Department")]
            public float Employees_Department { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"DepartmentID")]
            public float DepartmentID { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"DocDate")]
            public DateTime DocDate { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"ExpenseDate")]
            public DateTime ExpenseDate { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"CuryUnitCost")]
            public float CuryUnitCost { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"IsFraud")]
            public bool IsFraud { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for ClaimExpenseFraudDetectionModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"RefNbr")]
            public float RefNbr { get; set; }

            [ColumnName(@"Employees Department")]
            public float Employees_Department { get; set; }

            [ColumnName(@"DepartmentID")]
            public float DepartmentID { get; set; }

            [ColumnName(@"DocDate")]
            public float DocDate { get; set; }

            [ColumnName(@"ExpenseDate")]
            public float ExpenseDate { get; set; }

            [ColumnName(@"CuryUnitCost")]
            public float CuryUnitCost { get; set; }

            [ColumnName(@"IsFraud")]
            public bool IsFraud { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public bool PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

            [ColumnName(@"Probability")]
            public float Probability { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath(".\\ML\\Models\\FraudDetection\\ClaimExpenseFraudDetectionModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
